DROP INDEX IF EXISTS idx_release_schedule_book_id;
DROP INDEX IF EXISTS idx_chapters_book_id;
DROP TABLE IF EXISTS books_genres;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS chapters;
DROP TABLE IF EXISTS release_schedule;
DROP TABLE IF EXISTS books;
DROP TYPE genre_type;
DROP TYPE language_type;
DROP TYPE day_type;